@startuml CU-N1-Servicios
' Nivel 1 - Expande: Gestionar servicios turisticos
title CU Nivel 1 - Gestionar servicios turisticos
left to right direction

actor "Prestador" as PRE
actor "Administrador" as ADM

rectangle "Gestionar servicios turisticos" {
  usecase "Registrar servicio" as S1
  usecase "Editar servicio" as S2
  usecase "Validar datos del servicio" as S3
  usecase "Despublicar servicio" as S4
  usecase "Republicar servicio" as S5
  usecase "Moderar servicio" as S6
}

PRE --> S1
PRE --> S2
PRE --> S4
PRE --> S5
ADM --> S6

S1 ..> S3 : <<include>>
S2 ..> S3 : <<include>>
' S6 standalone de Admin, sin extend cruzando actores
@enduml
